baseURL = 'https://blog.leechdraw.me/'
languageCode = 'en-us'
title = 'Cat blog'
theme = 'ananke'
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
mainSections = "story"

[services.disqus]
shortname = 'leechdraw'
