baseURL = 'https://blog.leechdraw.me/'
languageCode = 'en-us'
title = 'Cat blog'
theme = 'ananke'
SectionPagesMenu = "main"
pagination.pageSize = 5 # this is set low for demonstrating with dummy content. Set to a higher number
mainSections = "story"

[services.disqus]
shortname = 'leechdraw'

[params]
custom_css = ["css/main.css"]
recent_posts_number = 5
show_reading_time = true
