name: Deploy Cat Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:

  tg_push:
    name: tg-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Get List Of Files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          since_last_remote_commit: true
          files: 'content/**'

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: steps.changed-markdown-files.outputs.added_files_count != '0'
        with:
          to: ${{ secrets.TG_GROUP }}
          token: ${{ secrets.TG_KEY }}
          message: |
            Кажется, выложили новый пост!
            Скорее бежим проверять!
            
      